name: Build MAUI Android APK (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Print dotnet info
        run: dotnet --info

      - name: Install MAUI workload (Android)
        run: dotnet workload install maui-android

      - name: Workload restore
        run: dotnet workload restore

      # Publicar genera el .apk empaquetado (más fiable que build)
      - name: Publish Debug APK
        run: dotnet publish MecNicaMauiLogin.csproj -f net8.0-android -c Debug -p:AndroidPackageFormat=apk -o out/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MecNicaMauiLogin-Debug-APK
          path: out/android/*.apk
